-- ?궗?슜?옄 ?깮?꽦 諛? 沅뚰븳 遺??뿬
-- CREATE USER FILOOM IDENTIFIED BY FILOOM;
-- GRANT CONNECT, RESOURCE TO FILOOM;
DROP TABLE BOOKING_SEAT_MAPPING CASCADE CONSTRAINTS;
DROP TABLE SEAT CASCADE CONSTRAINTS;

-- 湲곗〈 ?뀒?씠釉? 諛? ?떆???뒪 ?궘?젣
DROP TABLE BOOKING_SEAT CASCADE CONSTRAINTS;
DROP TABLE BOOKING CASCADE CONSTRAINTS;
DROP TABLE PLAYING CASCADE CONSTRAINTS;
DROP TABLE SCREEN_SEAT CASCADE CONSTRAINTS;
DROP TABLE SCREEN CASCADE CONSTRAINTS;
DROP TABLE FAVORITE CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE POSTER CASCADE CONSTRAINTS;
DROP TABLE MOVIE CASCADE CONSTRAINTS;
DROP TABLE APPLICANT CASCADE CONSTRAINTS;
DROP TABLE COUPON_USER CASCADE CONSTRAINTS;
DROP TABLE COUPON CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE EVENT_ATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
--DROP TABLE CATEGORY CASCADE CONSTRAINTS; --?븘?슂?뾾?쓬
DROP TABLE CERT CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_UNO;
DROP SEQUENCE SEQ_MNO;
DROP SEQUENCE SEQ_IMG;
DROP SEQUENCE SEQ_REV;
DROP SEQUENCE SEQ_ANO;
DROP SEQUENCE SEQ_NNO;
DROP SEQUENCE SEQ_ENO;
DROP SEQUENCE SEQ_EFNO;
DROP SEQUENCE SEQ_ERNO;
DROP SEQUENCE SEQ_CNO;
--DROP SEQUENCE SEQ_CAT; --?븘?슂?뾾?쓬
DROP SEQUENCE SEQ_BNO;
DROP SEQUENCE SEQ_SCR;
--DROP SEQUENCE SEQ_SEA; --議댁옱?븯吏? ?븡?뒗 ?떆???뒪?엫
DROP SEQUENCE SEQ_PLA;
DROP SEQUENCE SEQ_SCRS;
DROP SEQUENCE SEQ_BSNO;

-- MEMBER ?뀒?씠釉? ?깮?꽦
CREATE TABLE MEMBER (
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30) NOT NULL,
    USER_PWD VARCHAR2(100) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    BIRTH VARCHAR2(8) NOT NULL,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    MARKETING CHAR(1) DEFAULT 'N' CHECK (MARKETING IN ('Y', 'N')),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
);
COMMENT ON COLUMN MEMBER.USER_NO IS '?쉶?썝踰덊샇';
COMMENT ON COLUMN MEMBER.USER_ID IS '?븘?씠?뵒';
COMMENT ON COLUMN MEMBER.USER_PWD IS '鍮꾨?踰덊샇';
COMMENT ON COLUMN MEMBER.USER_NAME IS '?씠由?';
COMMENT ON COLUMN MEMBER.EMAIL IS '?씠硫붿씪';
COMMENT ON COLUMN MEMBER.BIRTH IS '?깮?뀈?썡?씪';
COMMENT ON COLUMN MEMBER.GENDER IS '?꽦蹂?';
COMMENT ON COLUMN MEMBER.MARKETING IS '留덉??똿?룞?쓽?뿬遺?';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '?쉶?썝媛??엯?씪';
COMMENT ON COLUMN MEMBER.STATUS IS '?긽?깭'; -- 'Y' : ?솢?꽦?솕 / 'N' : 鍮꾪솢?꽦?솕(?깉?눜)
CREATE SEQUENCE SEQ_UNO NOCACHE;

-- CERT ?뀒?씠釉? ?깮?꽦
CREATE TABLE CERT (
    CERT_NUM VARCHAR2(100) NOT NULL,
    USER_EMAIL VARCHAR2(200) NOT NULL,
    CREATE_DATE DATE NOT NULL
);
COMMENT ON COLUMN CERT.CERT_NUM IS '?씤利앸쾲?샇';
COMMENT ON COLUMN CERT.USER_EMAIL IS '?쉶?썝?씠硫붿씪';
COMMENT ON COLUMN CERT.CREATE_DATE IS '?깮?꽦?궇吏?';





-- CATEGORY ?뀒?씠釉? ?깮?꽦
/*
CREATE TABLE CATEGORY(
  CATEGORY_NO NUMBER PRIMARY KEY,
  CATEGORY_NAME VARCHAR2(30) NOT NULL
);
COMMENT ON COLUMN CATEGORY.CATEGORY_NO IS '#';
COMMENT ON COLUMN CATEGORY.CATEGORY_NAME IS '#';
CREATE SEQUENCE SEQ_CAT NOCACHE; */

-- NOTICE ?뀒?씠釉? ?깮?꽦
CREATE TABLE NOTICE(
  NOTICE_NO NUMBER PRIMARY KEY,
  NOTICE_TITLE VARCHAR2(200) NOT NULL,
  NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
  CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
  COUNT NUMBER DEFAULT 0,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
);
COMMENT ON COLUMN NOTICE.NOTICE_NO IS '#';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '#';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '#';
COMMENT ON COLUMN NOTICE.CREATE_DATE IS '#';
COMMENT ON COLUMN NOTICE.COUNT IS '#';
COMMENT ON COLUMN NOTICE.STATUS IS '#';
CREATE SEQUENCE SEQ_NNO NOCACHE;

-- EVENT ?뀒?씠釉? ?깮?꽦
CREATE TABLE EVENT(
  EVENT_NO NUMBER PRIMARY KEY,
  EVENT_TITLE VARCHAR2(200) NOT NULL,
  EVENT_CONTENT VARCHAR2(4000) NOT NULL,
  START_DATE DATE,
  END_DATE DATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  EVENT_STATUS VARCHAR2(1) DEFAULT 'N' CHECK(EVENT_STATUS IN ('Y', 'N')),
  EVENT_TYPE NUMBER CHECK(EVENT_TYPE IN (1, 2, 3)) -- 1 ?뙎湲?, 2 踰꾪듉, 3 ?삤?봽?씪?씤
);
COMMENT ON COLUMN EVENT.EVENT_NO IS '寃뚯떆湲?踰덊샇';
COMMENT ON COLUMN EVENT.EVENT_TITLE IS '寃뚯떆湲??젣紐?';
COMMENT ON COLUMN EVENT.EVENT_CONTENT IS '寃뚯떆湲??궡?슜';
COMMENT ON COLUMN EVENT.START_DATE IS '?씠踰ㅽ듃?떆?옉?씪';
COMMENT ON COLUMN EVENT.END_DATE IS '?씠踰ㅽ듃醫낅즺?씪';
COMMENT ON COLUMN EVENT.STATUS IS '寃뚯떆湲??긽?깭媛?';
COMMENT ON COLUMN EVENT.EVENT_STATUS IS '?씠踰ㅽ듃醫낅즺?뿬遺?';
COMMENT ON COLUMN EVENT.EVENT_TYPE IS '?씠踰ㅽ듃???엯';
CREATE SEQUENCE SEQ_ENO NOCACHE;

-- APPLICANT ?뀒?씠釉? ?깮?꽦
CREATE TABLE APPLICANT(
  APPLICANT_NO NUMBER PRIMARY KEY,      
  REF_ENO NUMBER NOT NULL,              
  USER_NO NUMBER NOT NULL,              
  APPLICATION_DATE DATE DEFAULT SYSDATE, 
  DRAWING_STATUS CHAR(1) DEFAULT 'N' CHECK(DRAWING_STATUS IN ('N', 'Y')),-- ?닔?젙 異붿꺼?뿬遺?
  FOREIGN KEY (REF_ENO) REFERENCES EVENT(EVENT_NO),
  FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);
COMMENT ON COLUMN APPLICANT.APPLICANT_NO IS '?쓳紐⑥옄踰덊샇';
COMMENT ON COLUMN APPLICANT.REF_ENO IS '李몄“寃뚯떆湲?踰덊샇';
COMMENT ON COLUMN APPLICANT.USER_NO IS '?쉶?썝踰덊샇';
COMMENT ON COLUMN APPLICANT.APPLICATION_DATE IS '?쓳紐⑦븳?궇吏?';
COMMENT ON COLUMN APPLICANT.DRAWING_STATUS IS '異붿꺼?뿬遺?';
CREATE SEQUENCE SEQ_ANO NOCACHE;

-- EVENT_ATTACHMENT ?뀒?씠釉? ?깮?꽦
CREATE TABLE EVENT_ATTACHMENT(
  EVENT_FILE_NO NUMBER PRIMARY KEY,
  REF_ENO NUMBER NOT NULL,
  ORIGIN_NAME VARCHAR2(300) NOT NULL,
  CHANGE_NAME VARCHAR2(300) NOT NULL,
  FILE_PATH VARCHAR2(1000) NOT NULL,
  UPLOAD_DATE DATE DEFAULT SYSDATE NOT NULL,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  FILE_LEVEL NUMBER DEFAULT 2 CHECK (FILE_LEVEL IN (1, 2)),
  FOREIGN KEY (REF_ENO) REFERENCES EVENT(EVENT_NO)
);
COMMENT ON COLUMN EVENT_ATTACHMENT.EVENT_FILE_NO IS '?뙆?씪踰덊샇';
COMMENT ON COLUMN EVENT_ATTACHMENT.REF_ENO IS '李몄“寃뚯떆湲?踰덊샇';
COMMENT ON COLUMN EVENT_ATTACHMENT.ORIGIN_NAME IS '?썝蹂몃챸';
COMMENT ON COLUMN EVENT_ATTACHMENT.CHANGE_NAME IS '?닔?젙紐?';
COMMENT ON COLUMN EVENT_ATTACHMENT.FILE_PATH IS '?뙆?씪???옣寃쎈줈';
COMMENT ON COLUMN EVENT_ATTACHMENT.UPLOAD_DATE IS '?뾽濡쒕뱶?궇吏?';
COMMENT ON COLUMN EVENT_ATTACHMENT.STATUS IS '?뙆?씪?긽?깭媛?';
COMMENT ON COLUMN EVENT_ATTACHMENT.FILE_LEVEL IS '?뙆?씪?젅踰?';
CREATE SEQUENCE SEQ_EFNO NOCACHE;

-- REPLY ?뀒?씠釉? ?깮?꽦
CREATE TABLE REPLY(
  REPLY_NO NUMBER PRIMARY KEY,
  REF_ENO NUMBER NOT NULL,
  REPLY_CONTENT VARCHAR2(4000) NOT NULL,
  REPLY_WRITER NUMBER NOT NULL,
  CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  DRAWING_STATUS CHAR(1) DEFAULT 'N' CHECK(DRAWING_STATUS IN ('N', 'Y')), -- ?닔?젙 異붿꺼?뿬遺? 
  FOREIGN KEY (REF_ENO) REFERENCES EVENT(EVENT_NO),
  FOREIGN KEY (REPLY_WRITER) REFERENCES MEMBER(USER_NO)
);
COMMENT ON COLUMN REPLY.REPLY_NO IS '?뙎湲?踰덊샇';
COMMENT ON COLUMN REPLY.REF_ENO IS '李몄“寃뚯떆湲?踰덊샇';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '?뙎湲??궡?슜';
COMMENT ON COLUMN REPLY.REPLY_WRITER IS '?뙎湲??옉?꽦?옄';
COMMENT ON COLUMN REPLY.CREATE_DATE IS '?뙎湲??옉?꽦?씪';
COMMENT ON COLUMN REPLY.STATUS IS '?뙎湲??긽?깭媛?';
COMMENT ON COLUMN REPLY.DRAWING_STATUS IS '異붿꺼?뿬遺?'; -- 異붽?
CREATE SEQUENCE SEQ_ERNO NOCACHE;

-- COUPON ?뀒?씠釉? ?깮?꽦
CREATE TABLE COUPON(
  COUPON_NO NUMBER PRIMARY KEY,
  COUPON_NAME VARCHAR2(300) NOT NULL,
  COUPON_EXP_DATE DATE DEFAULT ADD_MONTHS(SYSDATE, 6),
  COUPON_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(COUPON_STATUS IN ('Y', 'N')),
  COUPON_LEVEL NUMBER CHECK(COUPON_LEVEL BETWEEN 1 AND 3),
  REF_ENO NUMBER,
  FOREIGN KEY (REF_ENO) REFERENCES EVENT(EVENT_NO)
);
COMMENT ON COLUMN COUPON.COUPON_NO IS '荑좏룿怨좎쑀踰덊샇 SEQ_CNO';
COMMENT ON COLUMN COUPON.COUPON_NAME IS '荑좏룿?씠由?';
COMMENT ON COLUMN COUPON.COUPON_EXP_DATE IS '荑좏룿 ?궗?슜 湲고븳 DEFAULT:SYSDATE+6媛쒖썡';
COMMENT ON COLUMN COUPON.COUPON_STATUS IS '荑좏룿?긽?깭媛? Y:?쑀?슚, X:臾댄슚 (愿?由ъ옄媛? ?쟾泥? 荑좏룿?쓣 ?궘?젣?븳寃쎌슦 X)';
COMMENT ON COLUMN COUPON.COUPON_LEVEL IS '荑좏룿?젅踰? 1臾대??떆?궗?쉶,2?쁺?솕愿??엺沅뚯쓳紐⑦븯湲?,3湲고??씠踰ㅽ듃';
COMMENT ON COLUMN COUPON.REF_ENO IS '?씠踰ㅽ듃寃뚯떆湲?踰덊샇 (?쇅?옒?궎)';
CREATE SEQUENCE SEQ_CNO NOCACHE;


-- MOVIE ?뀒?씠釉? ?깮?꽦


CREATE TABLE MOVIE(
    MOVIE_NO        NUMBER          PRIMARY KEY,
    MOVIE_TITLE     VARCHAR2(200)   NOT NULL,
    PREMIERE        CHAR(1)         DEFAULT 'N' CHECK(PREMIERE IN ('Y', 'N')) NOT NULL,
    OPEN_DATE       DATE            NOT NULL,
    DIRECTOR        VARCHAR2(50)    NOT NULL,
    GENRE           VARCHAR2(200),
    RUNTIME         NUMBER          NOT NULL,
    SCREEN_TYPE     VARCHAR2(200),
    FILM_RATE       NUMBER          CHECK(FILM_RATE IN (3,12,15,19)) NOT NULL,
    DESCRIPTION     VARCHAR2(2000),
    STARRING        VARCHAR2(500),
    STATUS          CHAR(1)         DEFAULT 'Y' CHECK(STATUS IN ('Y','N')),
    TRAILER         VARCHAR2(500)
);
COMMENT ON COLUMN MOVIE.MOVIE_NO IS '?쁺?솕踰덊샇 ?떆???뒪';
COMMENT ON COLUMN MOVIE.MOVIE_TITLE IS '?쁺?솕 ?젣紐?';
COMMENT ON COLUMN MOVIE.PREMIERE IS '?긽?쁺?뿬遺? Y,N';
COMMENT ON COLUMN MOVIE.OPEN_DATE IS '媛쒕큺?씪?옄';
COMMENT ON COLUMN MOVIE.DIRECTOR IS '媛먮룆';
COMMENT ON COLUMN MOVIE.GENRE IS '?옣瑜?';
COMMENT ON COLUMN MOVIE.RUNTIME IS '?윭?떇???엫 (?젙?닔?삎)';
COMMENT ON COLUMN MOVIE.SCREEN_TYPE IS '2D ?씠?쇅?쓽 異붽? ?긽?쁺 ???엯 (IMAX, 4DX, SCREENX)';
COMMENT ON COLUMN MOVIE.FILM_RATE IS '?긽?쁺?벑湲? (3[?쟾泥?]/12/15/19)';
COMMENT ON COLUMN MOVIE.DESCRIPTION IS '?쁺?솕?꽕紐?';
COMMENT ON COLUMN MOVIE.STARRING IS '異쒖뿰?옄?젙蹂?';
COMMENT ON COLUMN MOVIE.STATUS IS '議댁냽?뿬遺? Y,N';
CREATE SEQUENCE SEQ_MNO NOCACHE;

-- POSTER ?뀒?씠釉? ?깮?꽦
CREATE TABLE POSTER(
    IMAGE_ID        NUMBER          PRIMARY KEY,
    MOVIE_NO        NUMBER          NOT NULL,
    FILE_NAME       VARCHAR2(1000)  NOT NULL,
    FILE_CODENAME   VARCHAR2(1000)  NOT NULL,
    IMAGE_PATH      VARCHAR2(1000),
    UPLOAD_DATE     DATE            DEFAULT SYSDATE,
    FILE_LEVEL      NUMBER          DEFAULT 2 CHECK(FILE_LEVEL IN (1,2)),
    STATUS          CHAR(1)         DEFAULT 'Y' CHECK(STATUS IN ('Y','N')),
    FOREIGN KEY(MOVIE_NO) REFERENCES MOVIE(MOVIE_NO)
);
COMMENT ON COLUMN POSTER.IMAGE_ID IS '?씠誘몄?踰덊샇 (?떆???뒪 SEQ_IMG)';
COMMENT ON COLUMN POSTER.MOVIE_NO IS '?쁺?솕踰덊샇';
COMMENT ON COLUMN POSTER.FILE_NAME IS '?썝蹂명뙆?씪紐?';
COMMENT ON COLUMN POSTER.FILE_CODENAME IS '?닔?젙?뙆?씪紐?';
COMMENT ON COLUMN POSTER.IMAGE_PATH IS '寃쎈줈+?닔?젙?뙆?씪紐?';
COMMENT ON COLUMN POSTER.UPLOAD_DATE IS '?뾽濡쒕뱶?씪?옄';
COMMENT ON COLUMN POSTER.FILE_LEVEL IS '?뙆?씪?젅踰? 1-?뜽?꽕?씪 2-湲고?';
COMMENT ON COLUMN POSTER.STATUS IS '?긽?깭媛?';
CREATE SEQUENCE SEQ_IMG NOCACHE;

-- REVIEW ?뀒?씠釉? ?깮?꽦
CREATE TABLE REVIEW(
    REVIEW_ID	    NUMBER	        PRIMARY KEY,
    USER_NO         NUMBER          NOT NULL,
    MOVIE_NO        NUMBER          NOT NULL,
    REVIEW_TITLE    VARCHAR2(200)   NOT NULL,
    REVIEW_DATE     DATE            DEFAULT SYSDATE,
    SCORE           NUMBER          CHECK(SCORE IN (1,2,3,4,5)) NOT NULL,
    IS_WATCHED      CHAR(1)         DEFAULT 'N' CHECK(IS_WATCHED IN ('Y', 'N')),
    REVIEW_CONTENT  VARCHAR2(2000)  NOT NULL,
    IS_DELETED      CHAR(1)         DEFAULT 'N' CHECK(IS_DELETED IN ('Y', 'N')),
    FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO),
    FOREIGN KEY(MOVIE_NO) REFERENCES MOVIE(MOVIE_NO)
);
COMMENT ON COLUMN REVIEW.REVIEW_ID IS '#';
COMMENT ON COLUMN REVIEW.USER_NO IS '#';
COMMENT ON COLUMN REVIEW.MOVIE_NO IS '#';
COMMENT ON COLUMN REVIEW.REVIEW_TITLE IS '#';
COMMENT ON COLUMN REVIEW.REVIEW_DATE IS '#';
COMMENT ON COLUMN REVIEW.SCORE IS '#';
COMMENT ON COLUMN REVIEW.IS_WATCHED IS '#';
COMMENT ON COLUMN REVIEW.REVIEW_CONTENT IS '#';
COMMENT ON COLUMN REVIEW.IS_DELETED IS '#';
CREATE SEQUENCE SEQ_REV NOCACHE;

-- FAVORITE ?뀒?씠釉? ?깮?꽦
CREATE TABLE FAVORITE(
    USER_NO NUMBER NOT NULL,
    MOVIE_NO NUMBER NOT NULL,
    FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO),
    FOREIGN KEY(MOVIE_NO) REFERENCES MOVIE(MOVIE_NO)
);
COMMENT ON COLUMN FAVORITE.USER_NO IS '#';
COMMENT ON COLUMN FAVORITE.MOVIE_NO IS '#';

-- BOOKING 예매내역테이블
CREATE TABLE BOOKING(
    BOOK_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    BOOK_DATE DATE DEFAULT SYSDATE NOT NULL,
    BOOK_TOTAL_COST NUMBER,
    BOOK_COST NUMBER,
    COST_PROCESS VARCHAR2(200),
    COST_TID VARCHAR2(200),
    STATUS CHAR(1) CHECK (STATUS IN ('Y', 'N')),
    MODIFY_DATE DATE,
    
    FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);
COMMENT ON COLUMN BOOKING.BOOK_NO IS '?쁺?솕?삁留ㅻ쾲?샇 SEQ_BNO';
COMMENT ON COLUMN BOOKING.USER_NO IS '?쉶?썝踰덊샇';
COMMENT ON COLUMN BOOKING.BOOK_DATE IS '?삁留ㅻ궇吏?';
COMMENT ON COLUMN BOOKING.BOOK_TOTAL_COST IS '珥앷툑?븸';
COMMENT ON COLUMN BOOKING.BOOK_COST IS '寃곗젣?맂 湲덉븸 (珥앷툑?븸-?븷?씤(荑좏룿))';
COMMENT ON COLUMN BOOKING.COST_PROCESS IS '寃곗젣諛⑹떇(移대뱶,怨꾩쥖,紐⑤컮?씪 ?벑)';
COMMENT ON COLUMN BOOKING.COST_TID IS '寃곗젣踰덊샇 (寃곗젣?떆 遺??뿬諛쏅뒗 踰덊샇,寃곗젣痍⑥냼?떆 ?븘?슂)';
COMMENT ON COLUMN BOOKING.STATUS IS 'Y,N(寃곗젣痍⑥냼?떆N)';
COMMENT ON COLUMN BOOKING.MODIFY_DATE IS '?닔?젙?궇吏?(寃곗젣痍⑥냼?궇吏?)';
CREATE SEQUENCE SEQ_BNO NOCACHE;

-- SCREEN ?뀒?씠釉? ?깮?꽦
CREATE TABLE SCREEN(
    SCREEN_NO NUMBER PRIMARY KEY,
    SCREEN_NAME VARCHAR2(50),
    SCREEN_CAPACITY NUMBER,
    SCREEN_INFO VARCHAR2(200)
);
COMMENT ON COLUMN SCREEN.SCREEN_NO IS '?긽?쁺愿?踰덊샇';
COMMENT ON COLUMN SCREEN.SCREEN_NAME IS '?긽?쁺愿??씠由?';
COMMENT ON COLUMN SCREEN.SCREEN_CAPACITY IS '?닔?슜?씤?썝';
COMMENT ON COLUMN SCREEN.SCREEN_INFO IS '?긽?쁺愿??젙蹂?';
CREATE SEQUENCE SEQ_SCR NOCACHE;

-- PLAYING ?뀒?씠釉? ?깮?꽦
CREATE TABLE PLAYING(
    PLAYING_NO NUMBER PRIMARY KEY,
    PLAYTIME DATE NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
    MOVIE_NO NUMBER NOT NULL,
    SCREEN_NO NUMBER NOT NULL,
    FOREIGN KEY (MOVIE_NO) REFERENCES MOVIE(MOVIE_NO),
    FOREIGN KEY (SCREEN_NO) REFERENCES SCREEN(SCREEN_NO)
);
COMMENT ON COLUMN PLAYING.PLAYING_NO IS '?긽?쁺踰덊샇 SEQ_PLA';
COMMENT ON COLUMN PLAYING.PLAYTIME IS '?긽?쁺?떆媛? DATE???엯';
COMMENT ON COLUMN PLAYING.STATUS IS '?궘?젣?뿬遺?';
COMMENT ON COLUMN PLAYING.MOVIE_NO IS '?쁺?솕踰덊샇';
COMMENT ON COLUMN PLAYING.SCREEN_NO IS '?긽?쁺愿?踰덊샇';
CREATE SEQUENCE SEQ_PLA NOCACHE;

-- SCREEN_SEAT ?뀒?씠釉? ?깮?꽦
CREATE TABLE SCREEN_SEAT(
    SSEAT_NO NUMBER PRIMARY KEY,
    SEAT_NO VARCHAR2(20) NOT NULL,
    SCREEN_NO NUMBER NOT NULL,
    FOREIGN KEY (SCREEN_NO) REFERENCES SCREEN(SCREEN_NO)
);
COMMENT ON COLUMN SCREEN_SEAT.SSEAT_NO IS '醫뚯꽍?씪?젹踰덊샇 SEQ_SCRS';
COMMENT ON COLUMN SCREEN_SEAT.SEAT_NO IS '醫뚯꽍踰덊샇';
COMMENT ON COLUMN SCREEN_SEAT.SCREEN_NO IS '?긽?쁺愿?踰덊샇';
CREATE SEQUENCE SEQ_SCRS NOCACHE;

-- BOOKING_SEAT ?뀒?씠釉? ?깮?꽦
CREATE TABLE BOOKING_SEAT(
    BOOKING_SEAT_NO NUMBER PRIMARY KEY,
    TIMELIMIT DATE,
    SSEAT_NO NUMBER NOT NULL,
    PLAYING_NO NUMBER NOT NULL,
    BOOK_NO NUMBER,
    FOREIGN KEY (SSEAT_NO) REFERENCES SCREEN_SEAT(SSEAT_NO),
    FOREIGN KEY (PLAYING_NO) REFERENCES PLAYING(PLAYING_NO),
    FOREIGN KEY (BOOK_NO) REFERENCES BOOKING(BOOK_NO)
);
COMMENT ON COLUMN BOOKING_SEAT.BOOKING_SEAT_NO IS '?긽?쁺醫뚯꽍 ?씪?젴踰덊샇 SEQ_BSNO';
COMMENT ON COLUMN BOOKING_SEAT.TIMELIMIT IS '?쑀?슚?떆媛?';
COMMENT ON COLUMN BOOKING_SEAT.SSEAT_NO IS '醫뚯꽍?씪?젹踰덊샇';
COMMENT ON COLUMN BOOKING_SEAT.PLAYING_NO IS '?쁺?솕?긽?쁺踰덊샇';
CREATE SEQUENCE SEQ_BSNO NOCACHE;

-- COUPON_USER ?뀒?씠釉? ?깮?꽦
CREATE TABLE COUPON_USER(
  COUPON_NO NUMBER,
  USER_NO NUMBER,
  BOOK_NO NUMBER,
  COUPON_USE CHAR(1) DEFAULT 'X' CHECK(COUPON_USE IN ('O', 'X')),
  FOREIGN KEY (COUPON_NO) REFERENCES COUPON(COUPON_NO),
  FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO),
  FOREIGN KEY (BOOK_NO) REFERENCES BOOKING(BOOK_NO)
);

COMMENT ON COLUMN COUPON_USER.COUPON_NO IS '荑좏룿踰덊샇';
COMMENT ON COLUMN COUPON_USER.USER_NO IS '?쉶?썝踰덊샇';
COMMENT ON COLUMN BOOKING.BOOK_NO IS '?삁留ㅻ쾲?샇';
COMMENT ON COLUMN COUPON_USER.COUPON_USE IS '荑좏룿?궗?슜?쑀臾? O-?궗?슜O X-?궗?슜X';

commit;