-- ?Ç¨?ö©?ûê ?Éù?Ñ± Î∞? Í∂åÌïú Î∂??ó¨
-- CREATE USER FILOOM IDENTIFIED BY FILOOM;
-- GRANT CONNECT, RESOURCE TO FILOOM;
DROP TABLE BOOKING_SEAT_MAPPING CASCADE CONSTRAINTS;
DROP TABLE SEAT CASCADE CONSTRAINTS;

-- Í∏∞Ï°¥ ?Öå?ù¥Î∏? Î∞? ?ãú???ä§ ?Ç≠?†ú
DROP TABLE BOOKING_SEAT CASCADE CONSTRAINTS;
DROP TABLE BOOKING CASCADE CONSTRAINTS;
DROP TABLE PLAYING CASCADE CONSTRAINTS;
DROP TABLE SCREEN_SEAT CASCADE CONSTRAINTS;
DROP TABLE SCREEN CASCADE CONSTRAINTS;
DROP TABLE FAVORITE CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE POSTER CASCADE CONSTRAINTS;
DROP TABLE MOVIE CASCADE CONSTRAINTS;
DROP TABLE APPLICANT CASCADE CONSTRAINTS;
DROP TABLE COUPON_USER CASCADE CONSTRAINTS;
DROP TABLE COUPON CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE EVENT_ATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
--DROP TABLE CATEGORY CASCADE CONSTRAINTS; --?ïÑ?öî?óÜ?ùå
DROP TABLE CERT CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_UNO;
DROP SEQUENCE SEQ_MNO;
DROP SEQUENCE SEQ_IMG;
DROP SEQUENCE SEQ_REV;
DROP SEQUENCE SEQ_ANO;
DROP SEQUENCE SEQ_NNO;
DROP SEQUENCE SEQ_ENO;
DROP SEQUENCE SEQ_EFNO;
DROP SEQUENCE SEQ_ERNO;
DROP SEQUENCE SEQ_CNO;
--DROP SEQUENCE SEQ_CAT; --?ïÑ?öî?óÜ?ùå
DROP SEQUENCE SEQ_BNO;
DROP SEQUENCE SEQ_SCR;
--DROP SEQUENCE SEQ_SEA; --Ï°¥Ïû¨?ïòÏß? ?ïä?äî ?ãú???ä§?ûÑ
DROP SEQUENCE SEQ_PLA;
DROP SEQUENCE SEQ_SCRS;
DROP SEQUENCE SEQ_BSNO;

-- MEMBER ?Öå?ù¥Î∏? ?Éù?Ñ±
CREATE TABLE MEMBER (
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30) NOT NULL,
    USER_PWD VARCHAR2(100) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    BIRTH VARCHAR2(8) NOT NULL,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    MARKETING CHAR(1) DEFAULT 'N' CHECK (MARKETING IN ('Y', 'N')),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
);
COMMENT ON COLUMN MEMBER.USER_NO IS '?öå?õêÎ≤àÌò∏';
COMMENT ON COLUMN MEMBER.USER_ID IS '?ïÑ?ù¥?îî';
COMMENT ON COLUMN MEMBER.USER_PWD IS 'ÎπÑÎ?Î≤àÌò∏';
COMMENT ON COLUMN MEMBER.USER_NAME IS '?ù¥Î¶?';
COMMENT ON COLUMN MEMBER.EMAIL IS '?ù¥Î©îÏùº';
COMMENT ON COLUMN MEMBER.BIRTH IS '?Éù?ÖÑ?õî?ùº';
COMMENT ON COLUMN MEMBER.GENDER IS '?Ñ±Î≥?';
COMMENT ON COLUMN MEMBER.MARKETING IS 'ÎßàÏ??åÖ?èô?ùò?ó¨Î∂?';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '?öå?õêÍ∞??ûÖ?ùº';
COMMENT ON COLUMN MEMBER.STATUS IS '?ÉÅ?Éú'; -- 'Y' : ?ôú?Ñ±?ôî / 'N' : ÎπÑÌôú?Ñ±?ôî(?Éà?á¥)
CREATE SEQUENCE SEQ_UNO NOCACHE;

-- CERT ?Öå?ù¥Î∏? ?Éù?Ñ±
CREATE TABLE CERT (
    CERT_NUM VARCHAR2(100) NOT NULL,
    USER_EMAIL VARCHAR2(200) NOT NULL,
    CREATE_DATE DATE NOT NULL
);
COMMENT ON COLUMN CERT.CERT_NUM IS '?ù∏Ï¶ùÎ≤à?ò∏';
COMMENT ON COLUMN CERT.USER_EMAIL IS '?öå?õê?ù¥Î©îÏùº';
COMMENT ON COLUMN CERT.CREATE_DATE IS '?Éù?Ñ±?Ç†Ïß?';





-- CATEGORY ?Öå?ù¥Î∏? ?Éù?Ñ±
/*
CREATE TABLE CATEGORY(
  CATEGORY_NO NUMBER PRIMARY KEY,
  CATEGORY_NAME VARCHAR2(30) NOT NULL
);
COMMENT ON COLUMN CATEGORY.CATEGORY_NO IS '#';
COMMENT ON COLUMN CATEGORY.CATEGORY_NAME IS '#';
CREATE SEQUENCE SEQ_CAT NOCACHE; */

-- NOTICE ?Öå?ù¥Î∏? ?Éù?Ñ±
CREATE TABLE NOTICE(
  NOTICE_NO NUMBER PRIMARY KEY,
  NOTICE_TITLE VARCHAR2(200) NOT NULL,
  NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
  CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
  COUNT NUMBER DEFAULT 0,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N'))
);
COMMENT ON COLUMN NOTICE.NOTICE_NO IS '#';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '#';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '#';
COMMENT ON COLUMN NOTICE.CREATE_DATE IS '#';
COMMENT ON COLUMN NOTICE.COUNT IS '#';
COMMENT ON COLUMN NOTICE.STATUS IS '#';
CREATE SEQUENCE SEQ_NNO NOCACHE;

-- EVENT ?Öå?ù¥Î∏? ?Éù?Ñ±
CREATE TABLE EVENT(
  EVENT_NO NUMBER PRIMARY KEY,
  EVENT_TITLE VARCHAR2(200) NOT NULL,
  EVENT_CONTENT VARCHAR2(4000) NOT NULL,
  START_DATE DATE,
  END_DATE DATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  EVENT_STATUS VARCHAR2(1) DEFAULT 'N' CHECK(EVENT_STATUS IN ('Y', 'N')),
  EVENT_TYPE NUMBER CHECK(EVENT_TYPE IN (1, 2, 3)) -- 1 ?åìÍ∏?, 2 Î≤ÑÌäº, 3 ?ò§?îÑ?ùº?ù∏
);
COMMENT ON COLUMN EVENT.EVENT_NO IS 'Í≤åÏãúÍ∏?Î≤àÌò∏';
COMMENT ON COLUMN EVENT.EVENT_TITLE IS 'Í≤åÏãúÍ∏??†úÎ™?';
COMMENT ON COLUMN EVENT.EVENT_CONTENT IS 'Í≤åÏãúÍ∏??Ç¥?ö©';
COMMENT ON COLUMN EVENT.START_DATE IS '?ù¥Î≤§Ìä∏?ãú?ûë?ùº';
COMMENT ON COLUMN EVENT.END_DATE IS '?ù¥Î≤§Ìä∏Ï¢ÖÎ£å?ùº';
COMMENT ON COLUMN EVENT.STATUS IS 'Í≤åÏãúÍ∏??ÉÅ?ÉúÍ∞?';
COMMENT ON COLUMN EVENT.EVENT_STATUS IS '?ù¥Î≤§Ìä∏Ï¢ÖÎ£å?ó¨Î∂?';
COMMENT ON COLUMN EVENT.EVENT_TYPE IS '?ù¥Î≤§Ìä∏???ûÖ';
CREATE SEQUENCE SEQ_ENO NOCACHE;

-- APPLICANT ?Öå?ù¥Î∏? ?Éù?Ñ±
CREATE TABLE APPLICANT(
  APPLICANT_NO NUMBER PRIMARY KEY,      
  REF_ENO NUMBER NOT NULL,              
  USER_NO NUMBER NOT NULL,              
  APPLICATION_DATE DATE DEFAULT SYSDATE, 
  DRAWING_STATUS CHAR(1) DEFAULT 'N' CHECK(DRAWING_STATUS IN ('N', 'Y')),-- ?àò?†ï Ï∂îÏ≤®?ó¨Î∂?
  FOREIGN KEY (REF_ENO) REFERENCES EVENT(EVENT_NO),
  FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);
COMMENT ON COLUMN APPLICANT.APPLICANT_NO IS '?ùëÎ™®ÏûêÎ≤àÌò∏';
COMMENT ON COLUMN APPLICANT.REF_ENO IS 'Ï∞∏Ï°∞Í≤åÏãúÍ∏?Î≤àÌò∏';
COMMENT ON COLUMN APPLICANT.USER_NO IS '?öå?õêÎ≤àÌò∏';
COMMENT ON COLUMN APPLICANT.APPLICATION_DATE IS '?ùëÎ™®Ìïú?Ç†Ïß?';
COMMENT ON COLUMN APPLICANT.DRAWING_STATUS IS 'Ï∂îÏ≤®?ó¨Î∂?';
CREATE SEQUENCE SEQ_ANO NOCACHE;

-- EVENT_ATTACHMENT ?Öå?ù¥Î∏? ?Éù?Ñ±
CREATE TABLE EVENT_ATTACHMENT(
  EVENT_FILE_NO NUMBER PRIMARY KEY,
  REF_ENO NUMBER NOT NULL,
  ORIGIN_NAME VARCHAR2(300) NOT NULL,
  CHANGE_NAME VARCHAR2(300) NOT NULL,
  FILE_PATH VARCHAR2(1000) NOT NULL,
  UPLOAD_DATE DATE DEFAULT SYSDATE NOT NULL,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  FILE_LEVEL NUMBER DEFAULT 2 CHECK (FILE_LEVEL IN (1, 2)),
  FOREIGN KEY (REF_ENO) REFERENCES EVENT(EVENT_NO)
);
COMMENT ON COLUMN EVENT_ATTACHMENT.EVENT_FILE_NO IS '?åå?ùºÎ≤àÌò∏';
COMMENT ON COLUMN EVENT_ATTACHMENT.REF_ENO IS 'Ï∞∏Ï°∞Í≤åÏãúÍ∏?Î≤àÌò∏';
COMMENT ON COLUMN EVENT_ATTACHMENT.ORIGIN_NAME IS '?õêÎ≥∏Î™Ö';
COMMENT ON COLUMN EVENT_ATTACHMENT.CHANGE_NAME IS '?àò?†ïÎ™?';
COMMENT ON COLUMN EVENT_ATTACHMENT.FILE_PATH IS '?åå?ùº???û•Í≤ΩÎ°ú';
COMMENT ON COLUMN EVENT_ATTACHMENT.UPLOAD_DATE IS '?óÖÎ°úÎìú?Ç†Ïß?';
COMMENT ON COLUMN EVENT_ATTACHMENT.STATUS IS '?åå?ùº?ÉÅ?ÉúÍ∞?';
COMMENT ON COLUMN EVENT_ATTACHMENT.FILE_LEVEL IS '?åå?ùº?†àÎ≤?';
CREATE SEQUENCE SEQ_EFNO NOCACHE;

-- REPLY ?Öå?ù¥Î∏? ?Éù?Ñ±
CREATE TABLE REPLY(
  REPLY_NO NUMBER PRIMARY KEY,
  REF_ENO NUMBER NOT NULL,
  REPLY_CONTENT VARCHAR2(4000) NOT NULL,
  REPLY_WRITER NUMBER NOT NULL,
  CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  DRAWING_STATUS CHAR(1) DEFAULT 'N' CHECK(DRAWING_STATUS IN ('N', 'Y')), -- ?àò?†ï Ï∂îÏ≤®?ó¨Î∂? 
  FOREIGN KEY (REF_ENO) REFERENCES EVENT(EVENT_NO),
  FOREIGN KEY (REPLY_WRITER) REFERENCES MEMBER(USER_NO)
);
COMMENT ON COLUMN REPLY.REPLY_NO IS '?åìÍ∏?Î≤àÌò∏';
COMMENT ON COLUMN REPLY.REF_ENO IS 'Ï∞∏Ï°∞Í≤åÏãúÍ∏?Î≤àÌò∏';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '?åìÍ∏??Ç¥?ö©';
COMMENT ON COLUMN REPLY.REPLY_WRITER IS '?åìÍ∏??ûë?Ñ±?ûê';
COMMENT ON COLUMN REPLY.CREATE_DATE IS '?åìÍ∏??ûë?Ñ±?ùº';
COMMENT ON COLUMN REPLY.STATUS IS '?åìÍ∏??ÉÅ?ÉúÍ∞?';
COMMENT ON COLUMN REPLY.DRAWING_STATUS IS 'Ï∂îÏ≤®?ó¨Î∂?'; -- Ï∂îÍ?
CREATE SEQUENCE SEQ_ERNO NOCACHE;

-- COUPON ?Öå?ù¥Î∏? ?Éù?Ñ±
CREATE TABLE COUPON(
  COUPON_NO NUMBER PRIMARY KEY,
  COUPON_NAME VARCHAR2(300) NOT NULL,
  COUPON_EXP_DATE DATE DEFAULT ADD_MONTHS(SYSDATE, 6),
  COUPON_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(COUPON_STATUS IN ('Y', 'N')),
  COUPON_LEVEL NUMBER CHECK(COUPON_LEVEL BETWEEN 1 AND 3),
  REF_ENO NUMBER,
  FOREIGN KEY (REF_ENO) REFERENCES EVENT(EVENT_NO)
);
COMMENT ON COLUMN COUPON.COUPON_NO IS 'Ïø†Ìè∞Í≥†Ïú†Î≤àÌò∏ SEQ_CNO';
COMMENT ON COLUMN COUPON.COUPON_NAME IS 'Ïø†Ìè∞?ù¥Î¶?';
COMMENT ON COLUMN COUPON.COUPON_EXP_DATE IS 'Ïø†Ìè∞ ?Ç¨?ö© Í∏∞Ìïú DEFAULT:SYSDATE+6Í∞úÏõî';
COMMENT ON COLUMN COUPON.COUPON_STATUS IS 'Ïø†Ìè∞?ÉÅ?ÉúÍ∞? Y:?ú†?ö®, X:Î¨¥Ìö® (Í¥?Î¶¨ÏûêÍ∞? ?†ÑÏ≤? Ïø†Ìè∞?ùÑ ?Ç≠?†ú?ïúÍ≤ΩÏö∞ X)';
COMMENT ON COLUMN COUPON.COUPON_LEVEL IS 'Ïø†Ìè∞?†àÎ≤? 1Î¨¥Î??ãú?Ç¨?öå,2?òÅ?ôîÍ¥??ûåÍ∂åÏùëÎ™®ÌïòÍ∏?,3Í∏∞Ì??ù¥Î≤§Ìä∏';
COMMENT ON COLUMN COUPON.REF_ENO IS '?ù¥Î≤§Ìä∏Í≤åÏãúÍ∏?Î≤àÌò∏ (?ô∏?ûò?Ç§)';
CREATE SEQUENCE SEQ_CNO NOCACHE;


-- MOVIE ?Öå?ù¥Î∏? ?Éù?Ñ±


CREATE TABLE MOVIE(
    MOVIE_NO        NUMBER          PRIMARY KEY,
    MOVIE_TITLE     VARCHAR2(200)   NOT NULL,
    PREMIERE        CHAR(1)         DEFAULT 'N' CHECK(PREMIERE IN ('Y', 'N')) NOT NULL,
    OPEN_DATE       DATE            NOT NULL,
    DIRECTOR        VARCHAR2(50)    NOT NULL,
    GENRE           VARCHAR2(200),
    RUNTIME         NUMBER          NOT NULL,
    SCREEN_TYPE     VARCHAR2(200),
    FILM_RATE       NUMBER          CHECK(FILM_RATE IN (3,12,15,19)) NOT NULL,
    DESCRIPTION     VARCHAR2(2000),
    STARRING        VARCHAR2(500),
    STATUS          CHAR(1)         DEFAULT 'Y' CHECK(STATUS IN ('Y','N')),
    TRAILER         VARCHAR2(500)
);
COMMENT ON COLUMN MOVIE.MOVIE_NO IS '?òÅ?ôîÎ≤àÌò∏ ?ãú???ä§';
COMMENT ON COLUMN MOVIE.MOVIE_TITLE IS '?òÅ?ôî ?†úÎ™?';
COMMENT ON COLUMN MOVIE.PREMIERE IS '?ÉÅ?òÅ?ó¨Î∂? Y,N';
COMMENT ON COLUMN MOVIE.OPEN_DATE IS 'Í∞úÎ¥â?ùº?ûê';
COMMENT ON COLUMN MOVIE.DIRECTOR IS 'Í∞êÎèÖ';
COMMENT ON COLUMN MOVIE.GENRE IS '?û•Î•?';
COMMENT ON COLUMN MOVIE.RUNTIME IS '?ü¨?ãù???ûÑ (?†ï?àò?òï)';
COMMENT ON COLUMN MOVIE.SCREEN_TYPE IS '2D ?ù¥?ô∏?ùò Ï∂îÍ? ?ÉÅ?òÅ ???ûÖ (IMAX, 4DX, SCREENX)';
COMMENT ON COLUMN MOVIE.FILM_RATE IS '?ÉÅ?òÅ?ì±Í∏? (3[?†ÑÏ≤?]/12/15/19)';
COMMENT ON COLUMN MOVIE.DESCRIPTION IS '?òÅ?ôî?Ñ§Î™?';
COMMENT ON COLUMN MOVIE.STARRING IS 'Ï∂úÏó∞?ûê?†ïÎ≥?';
COMMENT ON COLUMN MOVIE.STATUS IS 'Ï°¥ÏÜç?ó¨Î∂? Y,N';
CREATE SEQUENCE SEQ_MNO NOCACHE;

-- POSTER ?Öå?ù¥Î∏? ?Éù?Ñ±
CREATE TABLE POSTER(
    IMAGE_ID        NUMBER          PRIMARY KEY,
    MOVIE_NO        NUMBER          NOT NULL,
    FILE_NAME       VARCHAR2(1000)  NOT NULL,
    FILE_CODENAME   VARCHAR2(1000)  NOT NULL,
    IMAGE_PATH      VARCHAR2(1000),
    UPLOAD_DATE     DATE            DEFAULT SYSDATE,
    FILE_LEVEL      NUMBER          DEFAULT 2 CHECK(FILE_LEVEL IN (1,2)),
    STATUS          CHAR(1)         DEFAULT 'Y' CHECK(STATUS IN ('Y','N')),
    FOREIGN KEY(MOVIE_NO) REFERENCES MOVIE(MOVIE_NO)
);
COMMENT ON COLUMN POSTER.IMAGE_ID IS '?ù¥ÎØ∏Ï?Î≤àÌò∏ (?ãú???ä§ SEQ_IMG)';
COMMENT ON COLUMN POSTER.MOVIE_NO IS '?òÅ?ôîÎ≤àÌò∏';
COMMENT ON COLUMN POSTER.FILE_NAME IS '?õêÎ≥∏Ìåå?ùºÎ™?';
COMMENT ON COLUMN POSTER.FILE_CODENAME IS '?àò?†ï?åå?ùºÎ™?';
COMMENT ON COLUMN POSTER.IMAGE_PATH IS 'Í≤ΩÎ°ú+?àò?†ï?åå?ùºÎ™?';
COMMENT ON COLUMN POSTER.UPLOAD_DATE IS '?óÖÎ°úÎìú?ùº?ûê';
COMMENT ON COLUMN POSTER.FILE_LEVEL IS '?åå?ùº?†àÎ≤? 1-?ç∏?Ñ§?ùº 2-Í∏∞Ì?';
COMMENT ON COLUMN POSTER.STATUS IS '?ÉÅ?ÉúÍ∞?';
CREATE SEQUENCE SEQ_IMG NOCACHE;

-- REVIEW ?Öå?ù¥Î∏? ?Éù?Ñ±
CREATE TABLE REVIEW(
    REVIEW_ID	    NUMBER	        PRIMARY KEY,
    USER_NO         NUMBER          NOT NULL,
    MOVIE_NO        NUMBER          NOT NULL,
    REVIEW_TITLE    VARCHAR2(200)   NOT NULL,
    REVIEW_DATE     DATE            DEFAULT SYSDATE,
    SCORE           NUMBER          CHECK(SCORE IN (1,2,3,4,5)) NOT NULL,
    IS_WATCHED      CHAR(1)         DEFAULT 'N' CHECK(IS_WATCHED IN ('Y', 'N')),
    REVIEW_CONTENT  VARCHAR2(2000)  NOT NULL,
    IS_DELETED      CHAR(1)         DEFAULT 'N' CHECK(IS_DELETED IN ('Y', 'N')),
    FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO),
    FOREIGN KEY(MOVIE_NO) REFERENCES MOVIE(MOVIE_NO)
);
COMMENT ON COLUMN REVIEW.REVIEW_ID IS '#';
COMMENT ON COLUMN REVIEW.USER_NO IS '#';
COMMENT ON COLUMN REVIEW.MOVIE_NO IS '#';
COMMENT ON COLUMN REVIEW.REVIEW_TITLE IS '#';
COMMENT ON COLUMN REVIEW.REVIEW_DATE IS '#';
COMMENT ON COLUMN REVIEW.SCORE IS '#';
COMMENT ON COLUMN REVIEW.IS_WATCHED IS '#';
COMMENT ON COLUMN REVIEW.REVIEW_CONTENT IS '#';
COMMENT ON COLUMN REVIEW.IS_DELETED IS '#';
CREATE SEQUENCE SEQ_REV NOCACHE;

-- FAVORITE ?Öå?ù¥Î∏? ?Éù?Ñ±
CREATE TABLE FAVORITE(
    USER_NO NUMBER NOT NULL,
    MOVIE_NO NUMBER NOT NULL,
    FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO),
    FOREIGN KEY(MOVIE_NO) REFERENCES MOVIE(MOVIE_NO)
);
COMMENT ON COLUMN FAVORITE.USER_NO IS '#';
COMMENT ON COLUMN FAVORITE.MOVIE_NO IS '#';

-- BOOKING øπ∏≈≥ªø™≈◊¿Ã∫Ì
CREATE TABLE BOOKING(
    BOOK_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    BOOK_DATE DATE DEFAULT SYSDATE NOT NULL,
    BOOK_TOTAL_COST NUMBER,
    BOOK_COST NUMBER,
    COST_PROCESS VARCHAR2(200),
    COST_TID VARCHAR2(200),
    STATUS CHAR(1) CHECK (STATUS IN ('Y', 'N')),
    MODIFY_DATE DATE,
    
    FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);
COMMENT ON COLUMN BOOKING.BOOK_NO IS '?òÅ?ôî?òàÎß§Î≤à?ò∏ SEQ_BNO';
COMMENT ON COLUMN BOOKING.USER_NO IS '?öå?õêÎ≤àÌò∏';
COMMENT ON COLUMN BOOKING.BOOK_DATE IS '?òàÎß§ÎÇ†Ïß?';
COMMENT ON COLUMN BOOKING.BOOK_TOTAL_COST IS 'Ï¥ùÍ∏à?ï°';
COMMENT ON COLUMN BOOKING.BOOK_COST IS 'Í≤∞Ï†ú?êú Í∏àÏï° (Ï¥ùÍ∏à?ï°-?ï†?ù∏(Ïø†Ìè∞))';
COMMENT ON COLUMN BOOKING.COST_PROCESS IS 'Í≤∞Ï†úÎ∞©Ïãù(Ïπ¥Îìú,Í≥ÑÏ¢å,Î™®Î∞î?ùº ?ì±)';
COMMENT ON COLUMN BOOKING.COST_TID IS 'Í≤∞Ï†úÎ≤àÌò∏ (Í≤∞Ï†ú?ãú Î∂??ó¨Î∞õÎäî Î≤àÌò∏,Í≤∞Ï†úÏ∑®ÏÜå?ãú ?ïÑ?öî)';
COMMENT ON COLUMN BOOKING.STATUS IS 'Y,N(Í≤∞Ï†úÏ∑®ÏÜå?ãúN)';
COMMENT ON COLUMN BOOKING.MODIFY_DATE IS '?àò?†ï?Ç†Ïß?(Í≤∞Ï†úÏ∑®ÏÜå?Ç†Ïß?)';
CREATE SEQUENCE SEQ_BNO NOCACHE;

-- SCREEN ?Öå?ù¥Î∏? ?Éù?Ñ±
CREATE TABLE SCREEN(
    SCREEN_NO NUMBER PRIMARY KEY,
    SCREEN_NAME VARCHAR2(50),
    SCREEN_CAPACITY NUMBER,
    SCREEN_INFO VARCHAR2(200)
);
COMMENT ON COLUMN SCREEN.SCREEN_NO IS '?ÉÅ?òÅÍ¥?Î≤àÌò∏';
COMMENT ON COLUMN SCREEN.SCREEN_NAME IS '?ÉÅ?òÅÍ¥??ù¥Î¶?';
COMMENT ON COLUMN SCREEN.SCREEN_CAPACITY IS '?àò?ö©?ù∏?õê';
COMMENT ON COLUMN SCREEN.SCREEN_INFO IS '?ÉÅ?òÅÍ¥??†ïÎ≥?';
CREATE SEQUENCE SEQ_SCR NOCACHE;

-- PLAYING ?Öå?ù¥Î∏? ?Éù?Ñ±
CREATE TABLE PLAYING(
    PLAYING_NO NUMBER PRIMARY KEY,
    PLAYTIME DATE NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
    MOVIE_NO NUMBER NOT NULL,
    SCREEN_NO NUMBER NOT NULL,
    FOREIGN KEY (MOVIE_NO) REFERENCES MOVIE(MOVIE_NO),
    FOREIGN KEY (SCREEN_NO) REFERENCES SCREEN(SCREEN_NO)
);
COMMENT ON COLUMN PLAYING.PLAYING_NO IS '?ÉÅ?òÅÎ≤àÌò∏ SEQ_PLA';
COMMENT ON COLUMN PLAYING.PLAYTIME IS '?ÉÅ?òÅ?ãúÍ∞? DATE???ûÖ';
COMMENT ON COLUMN PLAYING.STATUS IS '?Ç≠?†ú?ó¨Î∂?';
COMMENT ON COLUMN PLAYING.MOVIE_NO IS '?òÅ?ôîÎ≤àÌò∏';
COMMENT ON COLUMN PLAYING.SCREEN_NO IS '?ÉÅ?òÅÍ¥?Î≤àÌò∏';
CREATE SEQUENCE SEQ_PLA NOCACHE;

-- SCREEN_SEAT ?Öå?ù¥Î∏? ?Éù?Ñ±
CREATE TABLE SCREEN_SEAT(
    SSEAT_NO NUMBER PRIMARY KEY,
    SEAT_NO VARCHAR2(20) NOT NULL,
    SCREEN_NO NUMBER NOT NULL,
    FOREIGN KEY (SCREEN_NO) REFERENCES SCREEN(SCREEN_NO)
);
COMMENT ON COLUMN SCREEN_SEAT.SSEAT_NO IS 'Ï¢åÏÑù?ùº?†¨Î≤àÌò∏ SEQ_SCRS';
COMMENT ON COLUMN SCREEN_SEAT.SEAT_NO IS 'Ï¢åÏÑùÎ≤àÌò∏';
COMMENT ON COLUMN SCREEN_SEAT.SCREEN_NO IS '?ÉÅ?òÅÍ¥?Î≤àÌò∏';
CREATE SEQUENCE SEQ_SCRS NOCACHE;

-- BOOKING_SEAT ?Öå?ù¥Î∏? ?Éù?Ñ±
CREATE TABLE BOOKING_SEAT(
    BOOKING_SEAT_NO NUMBER PRIMARY KEY,
    TIMELIMIT DATE,
    SSEAT_NO NUMBER NOT NULL,
    PLAYING_NO NUMBER NOT NULL,
    BOOK_NO NUMBER,
    FOREIGN KEY (SSEAT_NO) REFERENCES SCREEN_SEAT(SSEAT_NO),
    FOREIGN KEY (PLAYING_NO) REFERENCES PLAYING(PLAYING_NO),
    FOREIGN KEY (BOOK_NO) REFERENCES BOOKING(BOOK_NO)
);
COMMENT ON COLUMN BOOKING_SEAT.BOOKING_SEAT_NO IS '?ÉÅ?òÅÏ¢åÏÑù ?ùº?†®Î≤àÌò∏ SEQ_BSNO';
COMMENT ON COLUMN BOOKING_SEAT.TIMELIMIT IS '?ú†?ö®?ãúÍ∞?';
COMMENT ON COLUMN BOOKING_SEAT.SSEAT_NO IS 'Ï¢åÏÑù?ùº?†¨Î≤àÌò∏';
COMMENT ON COLUMN BOOKING_SEAT.PLAYING_NO IS '?òÅ?ôî?ÉÅ?òÅÎ≤àÌò∏';
CREATE SEQUENCE SEQ_BSNO NOCACHE;

-- COUPON_USER ?Öå?ù¥Î∏? ?Éù?Ñ±
CREATE TABLE COUPON_USER(
  COUPON_NO NUMBER,
  USER_NO NUMBER,
  BOOK_NO NUMBER,
  COUPON_USE CHAR(1) DEFAULT 'X' CHECK(COUPON_USE IN ('O', 'X')),
  FOREIGN KEY (COUPON_NO) REFERENCES COUPON(COUPON_NO),
  FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO),
  FOREIGN KEY (BOOK_NO) REFERENCES BOOKING(BOOK_NO)
);

COMMENT ON COLUMN COUPON_USER.COUPON_NO IS 'Ïø†Ìè∞Î≤àÌò∏';
COMMENT ON COLUMN COUPON_USER.USER_NO IS '?öå?õêÎ≤àÌò∏';
COMMENT ON COLUMN BOOKING.BOOK_NO IS '?òàÎß§Î≤à?ò∏';
COMMENT ON COLUMN COUPON_USER.COUPON_USE IS 'Ïø†Ìè∞?Ç¨?ö©?ú†Î¨? O-?Ç¨?ö©O X-?Ç¨?ö©X';

commit;