
--회원 1명
INSERT INTO "FILOOM"."MEMBER" (USER_NO, USER_ID, USER_PWD, USER_NAME, GENDER, BIRTH, EMAIL, ENROLL_DATE, STATUS) VALUES ('1', '123', '123', '일이삼', 'M', '19920325', '123@naver.com', TO_DATE('2024-12-12 13:21:19', 'YYYY-MM-DD HH24:MI:SS'), 'Y');



--영화목록
INSERT INTO "FILOOM"."MOVIE" (MOVIE_NO, MOVIE_TITLE, PREMIERE, OPEN_DATE, DIRECTOR, GENRE, RUNTIME, SCREEN_TYPE, FILM_RATE, DESCRIPTION, STARRING, STATUS) VALUES ('1', '조커', 'Y', TO_DATE('2024-12-11 17:56:52', 'YYYY-MM-DD HH24:MI:SS'), '봉준호', '액션', '120', '2D', '19', '영화설명~~~~~~', '출연자정보~~~~~', 'Y');


--영화 이미지
INSERT INTO "FILOOM"."POSTER" (IMAGE_ID, MOVIE_NO, FILE_NAME, FILE_CODENAME, IMAGE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES ('1', '1', 'ORIGINFILENAME', 'CHANGEFILENAME', '/FILOOM/RESOURCES/CHANGEFILENAME', TO_DATE('2024-12-11 18:14:15', 'YYYY-MM-DD HH24:MI:SS'), '1', 'Y');


--상영관정보

INSERT INTO "FILOOM"."SCREEN" (SCREEN_NO, SCREEN_NAME, SCREEN_CAPACITY,SCREEN_INFO) VALUES ('1', '1관', '50','상영관정보를 담을수 있는공간');

--스크린시트 테이블
INSERT INTO "FILOOM"."SCREEN_SEAT" (SSEAT_NO, SEAT_NO, SCREEN_NO) VALUES ('1', 'L1-1', '1');
INSERT INTO "FILOOM"."SCREEN_SEAT" (SSEAT_NO, SEAT_NO, SCREEN_NO) VALUES ('2', 'L2-2', '1');
INSERT INTO "FILOOM"."SCREEN_SEAT" (SSEAT_NO, SEAT_NO, SCREEN_NO) VALUES ('3', 'M1-3', '1');
INSERT INTO "FILOOM"."SCREEN_SEAT" (SSEAT_NO, SEAT_NO, SCREEN_NO) VALUES ('4', 'M2-4', '1');

--PLAYING 상영정보
INSERT INTO "FILOOM"."PLAYING" (PLAYING_NO, PLAYTIME, STATUS, MOVIE_NO, SCREEN_NO) VALUES ('1', TO_DATE('2024-12-25 13:57:05', 'YYYY-MM-DD HH24:MI:SS'), 'Y', '1', '1');

--상영,좌석
INSERT INTO "FILOOM"."BOOKING_SEAT" (BOOKING_SEAT_NO, TIMELIMIT, SSEAT_NO, PLAYING_NO) VALUES ('1', TO_DATE('2024-12-31 13:00:56', 'YYYY-MM-DD HH24:MI:SS'), '1', '1');
INSERT INTO "FILOOM"."BOOKING_SEAT" (BOOKING_SEAT_NO, TIMELIMIT, SSEAT_NO, PLAYING_NO) VALUES ('2', TO_DATE('2024-12-31 13:01:50', 'YYYY-MM-DD HH24:MI:SS'), '2', '1');
INSERT INTO "FILOOM"."BOOKING_SEAT" (BOOKING_SEAT_NO, TIMELIMIT, SSEAT_NO, PLAYING_NO) VALUES ('3', TO_DATE('2024-12-10 16:04:16', 'YYYY-MM-DD HH24:MI:SS'), '1', '1');
INSERT INTO "FILOOM"."BOOKING_SEAT" (BOOKING_SEAT_NO, TIMELIMIT, SSEAT_NO, PLAYING_NO) VALUES ('4', TO_DATE('2024-12-10 16:05:07', 'YYYY-MM-DD HH24:MI:SS'), '2', '1');


--쿠폰 생성
INSERT INTO "FILOOM"."COUPON" (COUPON_NO, COUPON_NAME, COUPON_STATUS, COUPON_LEVEL) VALUES ('900', '웰컴쿠폰', 'Y', '1');
INSERT INTO "FILOOM"."COUPON" (COUPON_NO, COUPON_NAME, COUPON_STATUS, COUPON_LEVEL) VALUES ('901', 'VIP쿠폰', 'Y', '1');
INSERT INTO "FILOOM"."COUPON" (COUPON_NO, COUPON_NAME, COUPON_STATUS, COUPON_LEVEL) VALUES ('902', '댓글이벤트쿠폰',  'Y', '1');


--유저 쿠폰 생성
INSERT INTO "FILOOM"."COUPON_USER" (COUPON_NO, USER_NO, COUPON_USE) VALUES ('900', '1', 'X');
INSERT INTO "FILOOM"."COUPON_USER" (COUPON_NO, USER_NO, COUPON_USE) VALUES ('901', '1', 'X');
INSERT INTO "FILOOM"."COUPON_USER" (COUPON_NO, USER_NO, COUPON_USE) VALUES ('902', '1', 'X');

COMMIT;




SELECT CU.* ,C.COUPON_NAME,C.COUPON_EXP_DATE
  FROM COUPON_USER CU
  JOIN COUPON C ON (CU.COUPON_NO = C.COUPON_NO)
 WHERE COUPON_EXP_DATE > SYSDATE
   AND USER_NO = 1
   AND BOOK_NO IS NULL
   AND COUPON_USE = 'X'
   
















