
--ȸ�� 1��
INSERT INTO "FILOOM"."MEMBER" (USER_NO, USER_ID, USER_PWD, USER_NAME, GENDER, BIRTH, EMAIL, ENROLL_DATE, STATUS) VALUES ('1', '123', '123', '���̻�', 'M', '19920325', '123@naver.com', TO_DATE('2024-12-12 13:21:19', 'YYYY-MM-DD HH24:MI:SS'), 'Y');



--��ȭ���
INSERT INTO "FILOOM"."MOVIE" (MOVIE_NO, MOVIE_TITLE, PREMIERE, OPEN_DATE, DIRECTOR, GENRE, RUNTIME, SCREEN_TYPE, FILM_RATE, DESCRIPTION, STARRING, STATUS) VALUES ('1', '��Ŀ', 'Y', TO_DATE('2024-12-11 17:56:52', 'YYYY-MM-DD HH24:MI:SS'), '����ȣ', '�׼�', '120', '2D', '19', '��ȭ����~~~~~~', '�⿬������~~~~~', 'Y');


--��ȭ �̹���
INSERT INTO "FILOOM"."POSTER" (IMAGE_ID, MOVIE_NO, FILE_NAME, FILE_CODENAME, IMAGE_PATH, UPLOAD_DATE, FILE_LEVEL, STATUS) VALUES ('1', '1', 'ORIGINFILENAME', 'joker.jpg', 'resources/images/posters', TO_DATE('2024-12-11 18:14:15', 'YYYY-MM-DD HH24:MI:SS'), '1', 'Y');


--�󿵰�����

INSERT INTO "FILOOM"."SCREEN" (SCREEN_NO, SCREEN_NAME, SCREEN_CAPACITY,SCREEN_INFO) VALUES ('1', '1��', '50','�󿵰������� ������ �ִ°���');

--��ũ����Ʈ ���̺�
INSERT INTO "FILOOM"."SCREEN_SEAT" (SSEAT_NO, SEAT_NO, SCREEN_NO) VALUES ('1', 'L1-1', '1');
INSERT INTO "FILOOM"."SCREEN_SEAT" (SSEAT_NO, SEAT_NO, SCREEN_NO) VALUES ('2', 'L2-2', '1');
INSERT INTO "FILOOM"."SCREEN_SEAT" (SSEAT_NO, SEAT_NO, SCREEN_NO) VALUES ('3', 'M1-3', '1');
INSERT INTO "FILOOM"."SCREEN_SEAT" (SSEAT_NO, SEAT_NO, SCREEN_NO) VALUES ('4', 'M2-4', '1');

--PLAYING ������
INSERT INTO "FILOOM"."PLAYING" (PLAYING_NO, PLAYTIME, STATUS, MOVIE_NO, SCREEN_NO) VALUES ('1', TO_DATE('2024-12-25 13:57:05', 'YYYY-MM-DD HH24:MI:SS'), 'Y', '1', '1');

--��,�¼�


--���� ����
INSERT INTO "FILOOM"."COUPON" (COUPON_NO, COUPON_NAME, COUPON_STATUS, COUPON_LEVEL,COUPON_EXP_DATE) VALUES ('10', '��������', 'Y', '1','25/06/19');
INSERT INTO "FILOOM"."COUPON" (COUPON_NO, COUPON_NAME, COUPON_STATUS, COUPON_LEVEL,COUPON_EXP_DATE) VALUES ('11', 'VIP����', 'Y', '1','25/06/31');
INSERT INTO "FILOOM"."COUPON" (COUPON_NO, COUPON_NAME, COUPON_STATUS, COUPON_LEVEL,COUPON_EXP_DATE) VALUES ('12', '�̺�Ʈ����',  'Y', '1','25/06/21');
INSERT INTO "FILOOM"."COUPON" (COUPON_NO, COUPON_NAME, COUPON_STATUS, COUPON_LEVEL,COUPON_EXP_DATE) VALUES ('13', '�������',  'Y', '1','25/06/22');
INSERT INTO "FILOOM"."COUPON" (COUPON_NO, COUPON_NAME, COUPON_STATUS, COUPON_LEVEL,COUPON_EXP_DATE) VALUES ('14', '����',  'Y', '1','25/06/32');
INSERT INTO "FILOOM"."COUPON" (COUPON_NO, COUPON_NAME, COUPON_STATUS, COUPON_LEVEL,COUPON_EXP_DATE) VALUES ('15', '�̺�Ʈ1����',  'Y', '1','25/06/24');
INSERT INTO "FILOOM"."COUPON" (COUPON_NO, COUPON_NAME, COUPON_STATUS, COUPON_LEVEL,COUPON_EXP_DATE) VALUES ('16', '�̺�Ʈ2����',  'Y', '1','25/06/25');


--���� ���� ����
INSERT INTO "FILOOM"."COUPON_USER" (COUPON_NO, USER_NO, COUPON_USE) VALUES ('10', '1', 'X');
INSERT INTO "FILOOM"."COUPON_USER" (COUPON_NO, USER_NO, COUPON_USE) VALUES ('11', '1', 'X');
INSERT INTO "FILOOM"."COUPON_USER" (COUPON_NO, USER_NO, COUPON_USE) VALUES ('12', '1', 'X');
INSERT INTO "FILOOM"."COUPON_USER" (COUPON_NO, USER_NO, COUPON_USE) VALUES ('13', '1', 'X');
INSERT INTO "FILOOM"."COUPON_USER" (COUPON_NO, USER_NO, COUPON_USE) VALUES ('14', '1', 'X');
INSERT INTO "FILOOM"."COUPON_USER" (COUPON_NO, USER_NO, COUPON_USE) VALUES ('15', '1', 'X');

COMMIT;



--�ʱ�ȭ ����

INSERT INTO "FILOOM"."BOOKING" (BOOK_NO, USER_NO, BOOK_DATE, BOOK_TOTAL_COST, BOOK_COST, COST_PROCESS, COST_TID, STATUS) VALUES (SEQ_BNO.NEXTVAL, '1', TO_DATE('2024-12-25 22:18:42', 'YYYY-MM-DD HH24:MI:SS'), '300', '300', 'CARD', 'dsfgadfasdf', 'Y')

SELECT COUNT(BOOK_NO)
		  FROM BOOKING B
		 JOIN MEMBER M ON (B.USER_NO = M.USER_NO)
         COMMIT;
         
         
         
         SELECT BOOKING_SEAT_NO,
 			   TO_CHAR(TIMELIMIT, 'YYYY-MM-DD HH24:MI:SS') AS TIMELIMIT,
 			   SEAT_NO
		  FROM BOOKING_SEAT BS
		  JOIN SCREEN_SEAT SS ON (BS.SSEAT_NO  = SS.SSEAT_NO)
		  JOIN PLAYING P ON (BS.PLAYING_NO = P.PLAYING_NO)
		 WHERE BS.BOOK_NO IS NULL
		   AND BS.PLAYING_NO = 1
		   